### ISSUE TITLE
[BUG] Performance

### ISSUE THREAD

**Issue by Phil061995** [vACDM/vacdm-plugin-v1#38]
Bad plugin performance today at EDDM during the entire day.

There was a bigger delay as usual for synchronisation as well as when clicking on item (e.g. to set ASAT + SUG took a couple of seconds). When setting ASRT or ASAT times were set initially but reset shortly thereafter. So it happened that you have to click several times on an item to set it.

The EDMM Package was used. Havn't had that bad performance at EDDF for a long time.

**Comment by Phil061995** [comment]
"When setting ASRT or ASAT times were set initially but reset shortly thereafter. So it happened that you have to click several times on an item to set it."

Happened in FRA several times today again.

**Comment by LeoKle** [comment]
> "When setting ASRT or ASAT times were set initially but reset shortly thereafter. So it happened that you have to click several times on an item to set it."

This due to the fact that the plugin first sets the local data and queues an update message, which will be send to the server on 5 sec intervals. After sending the updates the plugin pulls the data from the server. If the server did not update the set time by then, it will replace the local set time again.

as v1.3.0 introduces a major refactor which improves performance, I will close this issue for now.
